sudo: required
dist: trusty

language: java
jdk: 
  - oraclejdk7

services:
  - docker

# authenticate docker hub and pull image from repo
before_install:
- docker login -e DCS_PaaS@dell.com -u dcspaas -p Docker@123

# start up and build inside container
script:
- WORKING_DIR=$(pwd)
- docker pull dcspaas/javawebapp:latest
- docker run -d -i --name javawebapp dcspaas/javawebapp:latest /bin/sh -c 'cd /usr/local/tomcat/javawebapp;'
- docker exec javawebapp git pull origin master
- docker exec javawebapp ant all

# commit image and push to docker hub
after_success:
- docker commit javawebapp dcspaas/javawebapp:latest
- docker create -P --name javawebapp dcspaas/javawebapp:latest catalina.sh run
- docker commit javawebapp dcspaas/javawebapp:latest 
- docker push dcspaas/javawebapp:latest