sudo: required
dist: trusty

language: java
jdk: 
  - oraclejdk7

services:
  - docker

# authenticate docker hub and pull image from repo
before_install:
- docker login -e DCS_PaaS@dell.com -u dcspaas -p Docker@123

# start up and build inside container
script:
- WORKING_DIR=$(pwd)
- docker pull dcspaas/javawebapp:latest
- docker run -it dcspaas/javawebapp:latest bash
- cd javawebapp/
- git pull origin master
- ant all
- exit
- CONTAINER_ID=$(docker ps -lq)

# commit image and push to docker hub
after_success:
- docker commit $CONTAINER_ID dcspaas/javawebapp:latest
- docker create -P dcspaas/javawebapp:latest catalina.sh run
- CONTAINER_ID=$(docker ps -lq)
- docker commit $CONTAINER_ID dcspaas/javawebapp:latest 
- docker push dcspaas/javawebapp:latest