sudo: required

language: java

dist: trusty
services:
  - docker

# authenticate docker hub and pull image from repo
before_install:
- docker login -e DCS_PaaS@dell.com -u dcspaas -p Docker@123


# run build.xml config script
script:
- ant all

# upload .war file to image and push to Docker hub
after_success:
- WORKING_DIR=$(pwd)
- docker pull tomcat:7
- docker run -d -P tomcat:7
- CONTAINER_ID=$(docker ps -lq)
- docker cp $WORKING_DIR/dist/javawebapp.war $CONTAINER_ID:/usr/local/tomcat/webapps/
- docker commit $CONTAINER_ID dcspaas/javawebapp:latest
- docker push dcspaas/javawebapp:latest